// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOW_ORIGIN?: string;
	CACHE_MAX_AGE?: number;
	PROXY_USER_AGENT?: string;
	THIRD_PARTY_CLIENTS_USER_AGENT?: string[];
	VALIDATE_PATHNAME?: boolean;
	VALIDATE_SIGN?: boolean;
	VALIDATE_REFERER?: boolean;
	VALIDATE_USER_AGENT?: boolean;
	RETURN_EMPTY_PIC_WHEN_ERROR?: boolean;
	PROXY_KEY?: string;
	BLACK_LIST_DOMAIN?: string[];
	MAX_CONTENT_LENGTH?: number;
	EXTRA_PROXY_HEADERS?: string | Record<string, Record<string, string>>;
	CF_POLISH?: 'lossy' | 'lossless' | 'off';
	TRANSPARENT_PROXY?: string | Record<string, string>;
	TRANSPARENT_PROXY_MODE?: 'path' | 'query';
	TRANSPARENT_PROXY_QUERY?: string;
	STRIP_VIA_FOR_USER_AGENTS?: string[];
	BLOCKED_VIA_PSEUDO_NAMES?: string[];
	MAX_URL_LENGTH?: number;
	PASS_USER_AGENT_FROM_REQUEST?: boolean;
}
