// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOW_ORIGIN?: string;
	PROXY_USER_AGENT?: string;
	THIRD_PARTY_CLIENTS_USER_AGENT?: string[];
	VALIDATE_PATHNAME?: boolean;
	VALIDATE_SIGN?: boolean;
	VALIDATE_REFERER?: boolean;
	RETURN_EMPTY_PIC_WHEN_ERROR?: boolean;
	PROXY_KEY?: string;
	BLACK_LIST_DOMAIN?: string[];
	MAX_CONTENT_LENGTH?: number;
	EXTRA_PROXY_HEADERS?: string | Record<string, Record<string, string>>;
}
