name = "misskey-media-proxy-worker"
main = "src/index.ts"
compatibility_date = "2023-09-18"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOW_ORIGIN = ""
PROXY_USER_AGENT = "MisskeyMediaProxy/Worker 0.3"
THIRD_PARTY_CLIENTS_USER_AGENT = ""
VALIDATE_PATHNAME = false
VALIDATE_SIGN = false
VALIDATE_REFERER = false
RETURN_EMPTY_PIC_WHEN_ERROR = false
BLACK_LIST_DOMAIN = ""
