export const GENERAL_CORS_HEADERS = {
	'Access-Control-Allow-Methods': 'GET,OPTIONS',
};

export const MIN_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
