export const PROXY_CONFIG = {
	ALLOW_ORIGIN: '',
	PROXY_USER_AGENT: '',
	PROXY_KEY: '',
	THIRD_PARTY_CLIENTS_USER_AGENT: [],
	VALIDATE_PATHNAME: true,
	VALIDATE_SIGN: false,
	VALIDATE_REFERER: false,
}
